/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "strain.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shm_strain_v1_StrainTelemetry, shm_strain_v1_StrainTelemetry, 2)


PB_BIND(shm_strain_v1_StrainTelemetry_StrainBatch, shm_strain_v1_StrainTelemetry_StrainBatch, 2)


PB_BIND(shm_strain_v1_StrainDeviceAttributes, shm_strain_v1_StrainDeviceAttributes, AUTO)



