/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHM_STRAIN_V1_STRAIN_PB_H_INCLUDED
#define PB_SHM_STRAIN_V1_STRAIN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shm_strain_v1_StrainTelemetry_StrainBatch {
    uint64_t timestamp; /* 首样本设备时间戳（毫秒） */
    uint32_t ch_no; /* 通道编号（从 1 开始） */
    uint32_t sample_interval_ms; /* 采样间隔（ms），100Hz=10, 50Hz=20, 20Hz=50 */
    pb_size_t values_count;
    float values[64]; /* 该通道的应变值数组（με） */
    bool has_temperature;
    float temperature; /* 该通道温度值（℃） */
    bool has_battery;
    uint32_t battery; /* 电池电量 0-100% */
    bool has_mode;
    uint32_t mode; /* 设备工作模式 */
    bool has_status;
    uint32_t status; /* 状态码，0=正常 */
} shm_strain_v1_StrainTelemetry_StrainBatch;

/* 遥测上报消息 */
typedef struct _shm_strain_v1_StrainTelemetry {
    bool has_strainBatch;
    shm_strain_v1_StrainTelemetry_StrainBatch strainBatch;
} shm_strain_v1_StrainTelemetry;

/* 属性上报消息 */
typedef struct _shm_strain_v1_StrainDeviceAttributes {
    char firmware_version[32]; /* 固件版本 */
    char serial_number[32]; /* 设备序列号 */
    char device_model[32]; /* 设备型号 */
    uint32_t channel_count; /* 通道数 */
    uint32_t sample_interval_ms; /* 采样间隔（ms），所有通道统一 */
} shm_strain_v1_StrainDeviceAttributes;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shm_strain_v1_StrainTelemetry_init_default {false, shm_strain_v1_StrainTelemetry_StrainBatch_init_default}
#define shm_strain_v1_StrainTelemetry_StrainBatch_init_default {0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, 0, false, 0, false, 0}
#define shm_strain_v1_StrainDeviceAttributes_init_default {"", "", "", 0, 0}
#define shm_strain_v1_StrainTelemetry_init_zero  {false, shm_strain_v1_StrainTelemetry_StrainBatch_init_zero}
#define shm_strain_v1_StrainTelemetry_StrainBatch_init_zero {0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, 0, false, 0, false, 0}
#define shm_strain_v1_StrainDeviceAttributes_init_zero {"", "", "", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define shm_strain_v1_StrainTelemetry_StrainBatch_timestamp_tag 1
#define shm_strain_v1_StrainTelemetry_StrainBatch_ch_no_tag 2
#define shm_strain_v1_StrainTelemetry_StrainBatch_sample_interval_ms_tag 3
#define shm_strain_v1_StrainTelemetry_StrainBatch_values_tag 4
#define shm_strain_v1_StrainTelemetry_StrainBatch_temperature_tag 5
#define shm_strain_v1_StrainTelemetry_StrainBatch_battery_tag 6
#define shm_strain_v1_StrainTelemetry_StrainBatch_mode_tag 7
#define shm_strain_v1_StrainTelemetry_StrainBatch_status_tag 8
#define shm_strain_v1_StrainTelemetry_strainBatch_tag 1
#define shm_strain_v1_StrainDeviceAttributes_firmware_version_tag 1
#define shm_strain_v1_StrainDeviceAttributes_serial_number_tag 2
#define shm_strain_v1_StrainDeviceAttributes_device_model_tag 3
#define shm_strain_v1_StrainDeviceAttributes_channel_count_tag 4
#define shm_strain_v1_StrainDeviceAttributes_sample_interval_ms_tag 5

/* Struct field encoding specification for nanopb */
#define shm_strain_v1_StrainTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  strainBatch,       1)
#define shm_strain_v1_StrainTelemetry_CALLBACK NULL
#define shm_strain_v1_StrainTelemetry_DEFAULT NULL
#define shm_strain_v1_StrainTelemetry_strainBatch_MSGTYPE shm_strain_v1_StrainTelemetry_StrainBatch

#define shm_strain_v1_StrainTelemetry_StrainBatch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   ch_no,             2) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_ms,   3) \
X(a, STATIC,   REPEATED, FLOAT,    values,            4) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature,       5) \
X(a, STATIC,   OPTIONAL, UINT32,   battery,           6) \
X(a, STATIC,   OPTIONAL, UINT32,   mode,              7) \
X(a, STATIC,   OPTIONAL, UINT32,   status,            8)
#define shm_strain_v1_StrainTelemetry_StrainBatch_CALLBACK NULL
#define shm_strain_v1_StrainTelemetry_StrainBatch_DEFAULT NULL

#define shm_strain_v1_StrainDeviceAttributes_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   serial_number,     2) \
X(a, STATIC,   SINGULAR, STRING,   device_model,      3) \
X(a, STATIC,   SINGULAR, UINT32,   channel_count,     4) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_ms,   5)
#define shm_strain_v1_StrainDeviceAttributes_CALLBACK NULL
#define shm_strain_v1_StrainDeviceAttributes_DEFAULT NULL

extern const pb_msgdesc_t shm_strain_v1_StrainTelemetry_msg;
extern const pb_msgdesc_t shm_strain_v1_StrainTelemetry_StrainBatch_msg;
extern const pb_msgdesc_t shm_strain_v1_StrainDeviceAttributes_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shm_strain_v1_StrainTelemetry_fields &shm_strain_v1_StrainTelemetry_msg
#define shm_strain_v1_StrainTelemetry_StrainBatch_fields &shm_strain_v1_StrainTelemetry_StrainBatch_msg
#define shm_strain_v1_StrainDeviceAttributes_fields &shm_strain_v1_StrainDeviceAttributes_msg

/* Maximum encoded size of messages (where known) */
#define SHM_STRAIN_V1_STRAIN_PB_H_MAX_SIZE       shm_strain_v1_StrainTelemetry_size
#define shm_strain_v1_StrainDeviceAttributes_size 111
#define shm_strain_v1_StrainTelemetry_StrainBatch_size 366
#define shm_strain_v1_StrainTelemetry_size       369

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
