# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstrain.proto\x12\rshm.strain.v1\"\xb8\x02\n\x0fStrainTelemetry\x12?\n\x0bstrainBatch\x18\x01 \x01(\x0b\x32*.shm.strain.v1.StrainTelemetry.StrainBatch\x1a\xe3\x01\n\x0bStrainBatch\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05\x63h_no\x18\x02 \x01(\r\x12\x1a\n\x12sample_interval_ms\x18\x03 \x01(\r\x12\x0e\n\x06values\x18\x04 \x03(\x02\x12\x18\n\x0btemperature\x18\x05 \x01(\x02H\x00\x88\x01\x01\x12\x14\n\x07\x62\x61ttery\x18\x06 \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04mode\x18\x07 \x01(\rH\x02\x88\x01\x01\x12\x13\n\x06status\x18\x08 \x01(\rH\x03\x88\x01\x01\x42\x0e\n\x0c_temperatureB\n\n\x08_batteryB\x07\n\x05_modeB\t\n\x07_status\"\x92\x01\n\x16StrainDeviceAttributes\x12\x18\n\x10\x66irmware_version\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x65vice_model\x18\x03 \x01(\t\x12\x15\n\rchannel_count\x18\x04 \x01(\r\x12\x1a\n\x12sample_interval_ms\x18\x05 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRAINTELEMETRY._serialized_start=32
  _STRAINTELEMETRY._serialized_end=344
  _STRAINTELEMETRY_STRAINBATCH._serialized_start=117
  _STRAINTELEMETRY_STRAINBATCH._serialized_end=344
  _STRAINDEVICEATTRIBUTES._serialized_start=347
  _STRAINDEVICEATTRIBUTES._serialized_end=493
# @@protoc_insertion_point(module_scope)
